### ISSUE TITLE
Use ES6 module imports instead of require to utilise tree-shaking?

### ISSUE THREAD

**Issue by barrymcgee** [juju/react-components#24]
This repo copies over the old convention of importing modules via `require()`.

Should we switch to using ES2015 convention of `import / export` so we can [utilise the benefits of tree-shaking](https://insights.untapt.com/webpack-import-require-and-you-3fd7f5ea93c0)?

**Comment by hatched** [comment]
There have been a few discussions about this and the end goal is that we want to eventually get to using import/export however right now it requires an additional transpilation step as the GUI will be requiring these these components so we'd loose the ability to treeshake it anyways. This is also complicated by us requiring the css in the components.

I expected us to use these components by using require with the following syntax:
```javascript
const basicTable = require('react-components/basic-table');
```

No tree shaking would be necessary as you're only actually importing the component paths you need. So by going to an import/export gives us more problems than solutions currently.

**Comment by huwshimi** [comment]
We're now at a spot where this makes sense.
